name: klexp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pytorch
  - pip
  - cpuonly
  - pip:
    - git+https://github.com/alisiahkoohi/kl-expansion
    - matplotlib
    - tensorboard
    - obspy
    - mpire
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - gitpython
    - termcolor
    - h5py
    - seaborn
    - notebook
    - pathlib
    - packaging
