name: klexp
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - pip:
    - git+https://github.com/alisiahkoohi/kl-expansion
    - matplotlib
    - numpy
    - scipy
    - tqdm
    - gitpython
    - h5py
    - seaborn
    - mpire
    - pathlib
